services:
  db:
    image: pgvector/pgvector:pg17
    container_name: postgres-rag
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myrag
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: rag_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d rag_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: